services:
  - type: web
    name: counseling-backend
    env: node
    rootDir: sartha-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
